import type { PageServerLoad } from './$types';

export const load = (({ url }) => {
    return {
        seo: {
            title: 'Shapez Visualizer',
            description: 'The purpose of this project is to provide a suite of tools to visualize and modify data used by or generated from the game.',
            keywords: ['Shapez', 'Shapez 2', 'Visualization', 'Tools'],
            og: {
                title: 'Shape Visualizer - A suite of tools to visualize and modify data used or generated by the game Shapez 2',
                type: 'website',
                image: `${url.origin}/favicon.png`,
                url: url.href,
            },
        },
    };
}) satisfies PageServerLoad;
