<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/buildings/MixerDefaultInternalVariant.gltf -s -k -P -t -u -r /models/buildings/
-->

<script
  module
  lang="ts"
>
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      MixerFoundation: THREE.Mesh
      MixerGlas: THREE.Mesh
      MixerRotator: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf<GLTFResult>('/models/buildings/MixerDefaultInternalVariant.gltf'))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  const gltf = load()
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="MixerFoundation"
      castShadow
      receiveShadow
      geometry={gltf.nodes.MixerFoundation.geometry}
      material={gltf.nodes.MixerFoundation.material}
      position={[0, 0.07, 0]}
    />
    <T.Mesh
      name="MixerGlas"
      castShadow
      receiveShadow
      geometry={gltf.nodes.MixerGlas.geometry}
      material={gltf.nodes.MixerGlas.material}
      position={[0, 0.07, -0.02]}
    />
    <T.Mesh
      name="MixerRotator"
      castShadow
      receiveShadow
      geometry={gltf.nodes.MixerRotator.geometry}
      material={gltf.nodes.MixerRotator.material}
      position={[-1, 0.09, 0.52]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
