/* eslint-disable */
/**
 * This file was automatically generated by prepare:schemas.
 * DO NOT MODIFY IT BY HAND.
 */

export type System = (string | null)[] | null;
export type SerializedPlayerBadge = {
  Title?: string | null;
  ImageId?: string | null;
  [k: string]: unknown;
} & SerializedPlayerBadge1;
export type SerializedPlayerBadge1 = {
  Title?: string | null;
  ImageId?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedResearchConfig = {
  BaseChunkLimitMultiplier?: number;
  BaseBlueprintRewardMultiplier?: number;
  MaxShapeLayers?: number;
  InitialResearchPoints?: number;
  ShapesConfigurationId?: string | null;
  ColorSchemeConfigurationId?: string | null;
  ResearchLevelsAreProgressive?: boolean;
  ResearchPointsGenerationMode?: 0 | 1 | 2;
  BlueprintCurrencyShapes?: SerializedBlueprintCurrencyShape;
  IntroductionWikiEntryId?: string | null;
  InitiallyUnlockedUpgrades?: System;
  TutorialConfig?: string | null;
  [k: string]: unknown;
} & SerializedResearchConfig1;
export type SerializedBlueprintCurrencyShape = SerializedBlueprintCurrencyShape1[] | null;
export type SerializedBlueprintCurrencyShape1 = {
  Shape?: string | null;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  Amount?: number;
  [k: string]: unknown;
} & SerializedBlueprintCurrencyShape2;
export type SerializedBlueprintCurrencyShape2 = {
  Shape?: string | null;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  Amount?: number;
  [k: string]: unknown;
} | null;
export type SerializedResearchConfig1 = {
  BaseChunkLimitMultiplier?: number;
  BaseBlueprintRewardMultiplier?: number;
  MaxShapeLayers?: number;
  InitialResearchPoints?: number;
  ShapesConfigurationId?: string | null;
  ColorSchemeConfigurationId?: string | null;
  ResearchLevelsAreProgressive?: boolean;
  ResearchPointsGenerationMode?: 0 | 1 | 2;
  BlueprintCurrencyShapes?: SerializedBlueprintCurrencyShape;
  IntroductionWikiEntryId?: string | null;
  InitiallyUnlockedUpgrades?: System;
  TutorialConfig?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgression = {
  Levels?: SerializedResearchProgressionLevels;
  SideQuestGroups?: SerializedResearchProgressionSideQuests;
  ScenarioContent?: SerializedResearchProgressionScenarioContent;
  LinearUpgrades?: SerializedResearchProgressionLinearUpgrades;
  WikiConfiguration?: GameCoreResearch;
  [k: string]: unknown;
} & SerializedResearchProgression1;
export type SerializedResearchProgressionLevels = {
  Levels?: SerializedResearchLevel;
  [k: string]: unknown;
} & SerializedResearchProgressionLevels1;
export type SerializedResearchLevel = SerializedResearchLevel1[] | null;
export type SerializedResearchLevel1 = {
  Definition?: SerializedResearchLevelDefinition;
  Lines?: SerializedResearchLevelLines;
  Rewards?: SerializedResearchLevelRewards;
  [k: string]: unknown;
} & SerializedResearchLevel2;
export type SerializedResearchLevelDefinition = {
  Id?: string | null;
  VideoId?: string | null;
  PreviewImageId?: string | null;
  Title?: string | null;
  Description?: string | null;
  WikiEntryId?: string | null;
  SignatureShape?: string | null;
  Icon?: string | null;
  [k: string]: unknown;
} & SerializedResearchLevelDefinition1;
export type SerializedResearchLevelDefinition1 = {
  Id?: string | null;
  VideoId?: string | null;
  PreviewImageId?: string | null;
  Title?: string | null;
  Description?: string | null;
  WikiEntryId?: string | null;
  SignatureShape?: string | null;
  Icon?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedResearchLevelLines = {
  Lines?: SerializedResearchLevelLine;
  [k: string]: unknown;
} & SerializedResearchLevelLines1;
export type SerializedResearchLevelLine = SerializedResearchLevelLine1[] | null;
export type SerializedResearchLevelLine1 = {
  ReusedAtNextMilestone?: boolean;
  ReusedAtNextMilestoneOffset?: number;
  ReusedAtSameMilestone?: boolean;
  ReusedAtSameMilestoneOffset?: number;
  ReusedForPlayerLevel?: boolean;
  StartingOffset?: number;
  Shapes?: SerializedResearchCostShapes;
  [k: string]: unknown;
} & SerializedResearchLevelLine2;
export type SerializedResearchCostShapes = SerializedResearchCostShapes1[] | null;
export type SerializedResearchCostShapes1 = {
  Shape?: string | null;
  Amount?: number;
  [k: string]: unknown;
} & SerializedResearchCostShapes2;
export type SerializedResearchCostShapes2 = {
  Shape?: string | null;
  Amount?: number;
  [k: string]: unknown;
} | null;
export type SerializedResearchLevelLine2 = {
  ReusedAtNextMilestone?: boolean;
  ReusedAtNextMilestoneOffset?: number;
  ReusedAtSameMilestone?: boolean;
  ReusedAtSameMilestoneOffset?: number;
  ReusedForPlayerLevel?: boolean;
  StartingOffset?: number;
  Shapes?: SerializedResearchCostShapes;
  [k: string]: unknown;
} | null;
export type SerializedResearchLevelLines1 = {
  Lines?: SerializedResearchLevelLine;
  [k: string]: unknown;
} | null;
export type SerializedResearchLevelRewards = {
  Rewards?: ISerializedResearchReward;
  [k: string]: unknown;
} & SerializedResearchLevelRewards1;
export type ISerializedResearchReward = ISerializedResearchReward1[] | null;
export type ISerializedResearchReward1 = {
  [k: string]: unknown;
} & ISerializedResearchReward2;
export type ISerializedResearchReward2 = {
  [k: string]: unknown;
} | null;
export type SerializedResearchLevelRewards1 = {
  Rewards?: ISerializedResearchReward;
  [k: string]: unknown;
} | null;
export type SerializedResearchLevel2 = {
  Definition?: SerializedResearchLevelDefinition;
  Lines?: SerializedResearchLevelLines;
  Rewards?: SerializedResearchLevelRewards;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionLevels1 = {
  Levels?: SerializedResearchLevel;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionSideQuests = {
  SideQuestGroups?: SerializedResearchProgressionSideQuestGroup;
  [k: string]: unknown;
} & SerializedResearchProgressionSideQuests1;
export type SerializedResearchProgressionSideQuestGroup = SerializedResearchProgressionSideQuestGroup1[] | null;
export type SerializedResearchProgressionSideQuestGroup1 = {
  Title?: string | null;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  SideQuests?: SerializedResearchSideQuest;
  [k: string]: unknown;
} & SerializedResearchProgressionSideQuestGroup2;
export type SerializedResearchSideQuest = SerializedResearchSideQuest1[] | null;
export type SerializedResearchSideQuest1 = {
  Id?: string | null;
  IsFollowupForLevel?: boolean;
  Rewards?: ISerializedResearchReward;
  Costs?: SerializedResearchCostShapes;
  [k: string]: unknown;
} & SerializedResearchSideQuest2;
export type SerializedResearchSideQuest2 = {
  Id?: string | null;
  IsFollowupForLevel?: boolean;
  Rewards?: ISerializedResearchReward;
  Costs?: SerializedResearchCostShapes;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionSideQuestGroup2 = {
  Title?: string | null;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  SideQuests?: SerializedResearchSideQuest;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionSideQuests1 = {
  SideQuestGroups?: SerializedResearchProgressionSideQuestGroup;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionScenarioContent = {
  UpgradeCategories?: System;
  ContentBundles?: SerializedResearchProgressionScenarioContentBundles;
  [k: string]: unknown;
} & SerializedResearchProgressionScenarioContent1;
export type SerializedResearchProgressionScenarioContentBundles =
  | SerializedResearchProgressionScenarioContentBundles1[]
  | null;
export type SerializedResearchProgressionScenarioContentBundles1 = {
  ContentBundle?: SerializedResearchProgressionSideUpgrade;
  [k: string]: unknown;
} & SerializedResearchProgressionScenarioContentBundles2;
export type SerializedResearchProgressionSideUpgrade = SerializedResearchProgressionSideUpgrade1[] | null;
export type SerializedResearchProgressionSideUpgrade1 = {
  Id?: string | null;
  PreviewImageId?: string | null;
  VideoId?: string | null;
  Title?: string | null;
  IconId?: string | null;
  Description?: string | null;
  Hidden?: boolean;
  Category?: string | null;
  LinkedConverter?: string | null;
  ShopDisplayMode?: 0 | 1 | 2;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  Rewards?: ISerializedResearchReward;
  Costs?: ISerializedResearchCost;
  [k: string]: unknown;
} & SerializedResearchProgressionSideUpgrade2;
export type ISerializedResearchCost = ISerializedResearchCost1[] | null;
export type ISerializedResearchCost1 = {
  [k: string]: unknown;
} & ISerializedResearchCost2;
export type ISerializedResearchCost2 = {
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionSideUpgrade2 = {
  Id?: string | null;
  PreviewImageId?: string | null;
  VideoId?: string | null;
  Title?: string | null;
  IconId?: string | null;
  Description?: string | null;
  Hidden?: boolean;
  Category?: string | null;
  LinkedConverter?: string | null;
  ShopDisplayMode?: 0 | 1 | 2;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  Rewards?: ISerializedResearchReward;
  Costs?: ISerializedResearchCost;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionScenarioContentBundles2 = {
  ContentBundle?: SerializedResearchProgressionSideUpgrade;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionScenarioContent1 = {
  UpgradeCategories?: System;
  ContentBundles?: SerializedResearchProgressionScenarioContentBundles;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionLinearUpgrades = {
  ConverterHubOutputCountUpgradeId?: string | null;
  ConverterHubOutputQualityUpgradeId?: string | null;
  HubInputSizeUpgradeId?: string | null;
  ShapeQuantityUpgradeId?: string | null;
  ChunkLimitAddUpgradeId?: string | null;
  ChunkLimitMultiplyUpgradeId?: string | null;
  SpeedsToLinearUpgradeMappings?: {
    [k: string]: string | null;
  } | null;
  LinearUpgrades?: SerializedResearchProgressionLinearUpgrade;
  [k: string]: unknown;
} & SerializedResearchProgressionLinearUpgrades1;
export type SerializedResearchProgressionLinearUpgrade = SerializedResearchProgressionLinearUpgrade1[] | null;
export type SerializedResearchProgressionLinearUpgrade1 = {
  Id?: string | null;
  Title?: string | null;
  DisplayType?: 0 | 1 | 2 | 3 | 4 | 5;
  Levels?: SerializedResearchProgressionLinearUpgradeLevel;
  Attribute?: string | null;
  Description?: string | null;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  Category?: string | null;
  [k: string]: unknown;
} & SerializedResearchProgressionLinearUpgrade2;
export type SerializedResearchProgressionLinearUpgradeLevel = SerializedResearchProgressionLinearUpgradeLevel1[] | null;
export type SerializedResearchProgressionLinearUpgradeLevel1 = {
  Value?: number;
  Cost?: ISerializedResearchCost1;
} & SerializedResearchProgressionLinearUpgradeLevel2;
export type SerializedResearchProgressionLinearUpgradeLevel2 = {
  Value?: number;
  Cost?: ISerializedResearchCost1;
} | null;
export type SerializedResearchProgressionLinearUpgrade2 = {
  Id?: string | null;
  Title?: string | null;
  DisplayType?: 0 | 1 | 2 | 3 | 4 | 5;
  Levels?: SerializedResearchProgressionLinearUpgradeLevel;
  Attribute?: string | null;
  Description?: string | null;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  Category?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgressionLinearUpgrades1 = {
  ConverterHubOutputCountUpgradeId?: string | null;
  ConverterHubOutputQualityUpgradeId?: string | null;
  HubInputSizeUpgradeId?: string | null;
  ShapeQuantityUpgradeId?: string | null;
  ChunkLimitAddUpgradeId?: string | null;
  ChunkLimitMultiplyUpgradeId?: string | null;
  SpeedsToLinearUpgradeMappings?: {
    [k: string]: string | null;
  } | null;
  LinearUpgrades?: SerializedResearchProgressionLinearUpgrade;
  [k: string]: unknown;
} | null;
export type GameCoreResearch = {
  Categories?: GameCoreResearch1;
  WikiEntries?: GameCoreResearch4;
  [k: string]: unknown;
} & GameCoreResearchSerializedWikiConfiguration;
export type GameCoreResearch1 = GameCoreResearch2[] | null;
export type GameCoreResearch2 = GameCoreResearch3[] | null;
export type GameCoreResearch3 = {
  Id?: string | null;
  IconId?: string | null;
  TitleId?: string | null;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  [k: string]: unknown;
} & GameCoreResearchSerializedWikiCategory;
export type GameCoreResearchSerializedWikiCategory = {
  Id?: string | null;
  IconId?: string | null;
  TitleId?: string | null;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  [k: string]: unknown;
} | null;
export type GameCoreResearch4 = GameCoreResearch5[] | null;
export type GameCoreResearch5 = GameCoreResearch6[] | null;
export type GameCoreResearch6 = {
  EntryId?: string | null;
  CategoryId?: string | null;
  RequiredMechanicIds?: System;
  RequiredUpgradeIds?: System;
  [k: string]: unknown;
} & GameCoreResearchSerializedUnlockableWikiReference;
export type GameCoreResearchSerializedUnlockableWikiReference = {
  EntryId?: string | null;
  CategoryId?: string | null;
  RequiredMechanicIds?: System;
  RequiredUpgradeIds?: System;
  [k: string]: unknown;
} | null;
export type GameCoreResearchSerializedWikiConfiguration = {
  Categories?: GameCoreResearch1;
  WikiEntries?: GameCoreResearch4;
  [k: string]: unknown;
} | null;
export type SerializedResearchProgression1 = {
  Levels?: SerializedResearchProgressionLevels;
  SideQuestGroups?: SerializedResearchProgressionSideQuests;
  ScenarioContent?: SerializedResearchProgressionScenarioContent;
  LinearUpgrades?: SerializedResearchProgressionLinearUpgrades;
  WikiConfiguration?: GameCoreResearch;
  [k: string]: unknown;
} | null;
export type SerializedStartingLocationData = {
  InitialViewport?: ViewportSerializedData;
  CentralElementCoordinate?: GameCoreCoordinates;
  InitialIslands?: SerializedStartingLocationDataInitialIslands;
  FixedPatches?: SerializedStartingLocationDataFixedPatches;
  StartingChunks?: SerializedStartingLocationDataStartingChunks;
  [k: string]: unknown;
} & SerializedStartingLocationData1;
export type ViewportSerializedData = {
  PositionX?: number;
  PositionY?: number;
  Zoom?: number;
  RotationDegrees?: number;
  Angle?: number;
  BuildingLayer?: number;
  IslandLayer?: number;
  ShowAllBuildingLayers?: boolean;
  ShowAllIslandLayers?: boolean;
  [k: string]: unknown;
} & ViewportSerializedData1;
export type ViewportSerializedData1 = {
  PositionX?: number;
  PositionY?: number;
  Zoom?: number;
  RotationDegrees?: number;
  Angle?: number;
  BuildingLayer?: number;
  IslandLayer?: number;
  ShowAllBuildingLayers?: boolean;
  ShowAllIslandLayers?: boolean;
  [k: string]: unknown;
} | null;
export type GameCoreCoordinates = {
  x?: number;
  y?: number;
  z?: number;
} & GameCoreCoordinatesGlobalChunkCoordinate;
export type GameCoreCoordinatesGlobalChunkCoordinate = {
  x?: number;
  y?: number;
  z?: number;
} | null;
export type SerializedStartingLocationDataInitialIslands = {
  InitialIslands?: SerializedStartingLocationDataInitialIsland;
  [k: string]: unknown;
} & SerializedStartingLocationDataInitialIslands1;
export type SerializedStartingLocationDataInitialIsland = SerializedStartingLocationDataInitialIsland1[] | null;
export type SerializedStartingLocationDataInitialIsland1 = {
  Position_GC?: GameCoreCoordinates;
  Rotation?: number;
  LayoutId?: string | null;
  [k: string]: unknown;
} & SerializedStartingLocationDataInitialIsland2;
export type SerializedStartingLocationDataInitialIsland2 = {
  Position_GC?: GameCoreCoordinates;
  Rotation?: number;
  LayoutId?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedStartingLocationDataInitialIslands1 = {
  InitialIslands?: SerializedStartingLocationDataInitialIsland;
  [k: string]: unknown;
} | null;
export type SerializedStartingLocationDataFixedPatches = {
  FixedPatches?: SerializedStartingLocationDataFixedPatch;
  [k: string]: unknown;
} & SerializedStartingLocationDataFixedPatches1;
export type SerializedStartingLocationDataFixedPatch = SerializedStartingLocationDataFixedPatch1[] | null;
export type SerializedStartingLocationDataFixedPatch1 = {
  Shape?: string | null;
  Position_LC?: GameCoreCoordinates1;
  LocalTiles?: GameCoreCoordinates2;
  [k: string]: unknown;
} & SerializedStartingLocationDataFixedPatch2;
export type GameCoreCoordinates1 = {
  x?: number;
  y?: number;
  z?: number;
} & GameCoreCoordinatesChunkVector;
export type GameCoreCoordinatesChunkVector = {
  x?: number;
  y?: number;
  z?: number;
} | null;
export type GameCoreCoordinates2 = GameCoreCoordinates1[] | null;
export type SerializedStartingLocationDataFixedPatch2 = {
  Shape?: string | null;
  Position_LC?: GameCoreCoordinates1;
  LocalTiles?: GameCoreCoordinates2;
  [k: string]: unknown;
} | null;
export type SerializedStartingLocationDataFixedPatches1 = {
  FixedPatches?: SerializedStartingLocationDataFixedPatch;
  [k: string]: unknown;
} | null;
export type SerializedStartingLocationDataStartingChunks = {
  StartingChunks?: SerializedStartingLocationDataStartingChunk;
  [k: string]: unknown;
} & SerializedStartingLocationDataStartingChunks1;
export type SerializedStartingLocationDataStartingChunk = SerializedStartingLocationDataStartingChunk1[] | null;
export type SerializedStartingLocationDataStartingChunk1 = {
  SuperChunk?: GameCoreCoordinates3;
  GuaranteedShapePatches?: System;
  GuaranteedColorPatches?: System1;
  [k: string]: unknown;
} & SerializedStartingLocationDataStartingChunk2;
export type GameCoreCoordinates3 = {
  x?: number;
  y?: number;
} & GameCoreCoordinatesSuperChunkCoordinate;
export type GameCoreCoordinatesSuperChunkCoordinate = {
  x?: number;
  y?: number;
} | null;
export type System1 = string[] | null;
export type SerializedStartingLocationDataStartingChunk2 = {
  SuperChunk?: GameCoreCoordinates3;
  GuaranteedShapePatches?: System;
  GuaranteedColorPatches?: System1;
  [k: string]: unknown;
} | null;
export type SerializedStartingLocationDataStartingChunks1 = {
  StartingChunks?: SerializedStartingLocationDataStartingChunk;
  [k: string]: unknown;
} | null;
export type SerializedStartingLocationData1 = {
  InitialViewport?: ViewportSerializedData;
  CentralElementCoordinate?: GameCoreCoordinates;
  InitialIslands?: SerializedStartingLocationDataInitialIslands;
  FixedPatches?: SerializedStartingLocationDataFixedPatches;
  StartingChunks?: SerializedStartingLocationDataStartingChunks;
  [k: string]: unknown;
} | null;
export type SerializedResearchPlayerLevelConfig = {
  IconicLevelShapes?: SerializedResearchPlayerLevelLevelShapes;
  IconicLevelShapeInterval?: number;
  GoalLines?: SerializedResearchPlayerLevelConfigGoalLine;
  Rewards?: SerializedResearchPlayerLevelConfigReward;
  [k: string]: unknown;
} & SerializedResearchPlayerLevelConfig1;
export type SerializedResearchPlayerLevelLevelShapes = {
  LevelShapes?: System;
  [k: string]: unknown;
} & SerializedResearchPlayerLevelLevelShapes1;
export type SerializedResearchPlayerLevelLevelShapes1 = {
  LevelShapes?: System;
  [k: string]: unknown;
} | null;
export type SerializedResearchPlayerLevelConfigGoalLine = SerializedResearchPlayerLevelConfigGoalLine1[] | null;
export type SerializedResearchPlayerLevelConfigGoalLine1 = {
  Id?: string | null;
  Randomized?: boolean;
  RandomizedUseCrystals?: boolean;
  RandomizedExtraShapesPer10Level?: System;
  Shape?: string | null;
  ConvertedShape?: string | null;
  StartingAmount?: number;
  ExponentialGrowthPercentPerLevel?: number;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  [k: string]: unknown;
} & SerializedResearchPlayerLevelConfigGoalLine2;
export type SerializedResearchPlayerLevelConfigGoalLine2 = {
  Id?: string | null;
  Randomized?: boolean;
  RandomizedUseCrystals?: boolean;
  RandomizedExtraShapesPer10Level?: System;
  Shape?: string | null;
  ConvertedShape?: string | null;
  StartingAmount?: number;
  ExponentialGrowthPercentPerLevel?: number;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  [k: string]: unknown;
} | null;
export type SerializedResearchPlayerLevelConfigReward = SerializedResearchPlayerLevelConfigReward1[] | null;
export type SerializedResearchPlayerLevelConfigReward1 = {
  MinimumLevel?: number;
  Rewards?: ISerializedResearchReward;
  [k: string]: unknown;
} & SerializedResearchPlayerLevelConfigReward2;
export type SerializedResearchPlayerLevelConfigReward2 = {
  MinimumLevel?: number;
  Rewards?: ISerializedResearchReward;
  [k: string]: unknown;
} | null;
export type SerializedResearchPlayerLevelConfig1 = {
  IconicLevelShapes?: SerializedResearchPlayerLevelLevelShapes;
  IconicLevelShapeInterval?: number;
  GoalLines?: SerializedResearchPlayerLevelConfigGoalLine;
  Rewards?: SerializedResearchPlayerLevelConfigReward;
  [k: string]: unknown;
} | null;
export type SerializedResearchMechanics = {
  Mechanics?: SerializedResearchMechanic;
  BuildingLayerMechanicIds?: System;
  IslandLayerMechanicIds?: System;
  IslandLayersUnlockOrder?: System2;
  BlueprintsMechanicId?: string | null;
  RailsMechanicId?: string | null;
  IslandManagementMechanicId?: string | null;
  PlayerLevelMechanicId?: string | null;
  TrainHubDeliveryMechanicId?: string | null;
  SideUpgradeMechanicId?: string | null;
  [k: string]: unknown;
} & SerializedResearchMechanics1;
export type SerializedResearchMechanic = SerializedResearchMechanic1[] | null;
export type SerializedResearchMechanic1 = {
  Id?: string | null;
  Title?: string | null;
  Description?: string | null;
  IconId?: string | null;
  [k: string]: unknown;
} & SerializedResearchMechanic2;
export type SerializedResearchMechanic2 = {
  Id?: string | null;
  Title?: string | null;
  Description?: string | null;
  IconId?: string | null;
  [k: string]: unknown;
} | null;
export type System2 = number[] | null;
export type SerializedResearchMechanics1 = {
  Mechanics?: SerializedResearchMechanic;
  BuildingLayerMechanicIds?: System;
  IslandLayerMechanicIds?: System;
  IslandLayersUnlockOrder?: System2;
  BlueprintsMechanicId?: string | null;
  RailsMechanicId?: string | null;
  IslandManagementMechanicId?: string | null;
  PlayerLevelMechanicId?: string | null;
  TrainHubDeliveryMechanicId?: string | null;
  SideUpgradeMechanicId?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedConvertersConfig = {
  RocketGroups?: SerializedRocketGroup;
  Configs?: {
    [k: string]: SerializedConverterConfig;
  } | null;
  [k: string]: unknown;
} & SerializedConvertersConfig1;
export type SerializedRocketGroup = SerializedRocketGroup1[] | null;
export type SerializedRocketGroup1 = {
  RocketGroupId?: string | null;
  IconId?: string | null;
  TitleId?: string | null;
  RocketIds?: System;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  [k: string]: unknown;
} & SerializedRocketGroup2;
export type SerializedRocketGroup2 = {
  RocketGroupId?: string | null;
  IconId?: string | null;
  TitleId?: string | null;
  RocketIds?: System;
  RequiredUpgradeIds?: System;
  RequiredMechanicIds?: System;
  [k: string]: unknown;
} | null;
export type SerializedConverterConfig = {
  Title?: string | null;
  Description?: string | null;
  Icon?: string | null;
  ChunkCost?: number;
  IsSelectable?: boolean;
  IsBuildable?: boolean;
  IsRemovable?: boolean;
  AccentColorPaletteIndex?: number;
  Modules?: SerializedConverterModule;
  SimpleAnimationModules?: SerializedConverterSimpleAnimationModule;
  IOs?: SerializedConverterIOs;
  Recipe?: SerializedConverterRecipe;
  [k: string]: unknown;
} & SerializedConverterConfig1;
export type SerializedConverterModule = SerializedConverterModule1[] | null;
export type SerializedConverterModule1 = {
  Transform?: SerializedTransform;
  Name?: string | null;
  [k: string]: unknown;
} & SerializedConverterModule2;
export type SerializedTransform = {
  X?: number;
  Y?: number;
  Z?: number;
  Rotation?: number;
  ToChunkTransform?: GameCoreCoordinates4;
  ToChunkPivot?: GameCoreCoordinates6;
} & SerializedTransform1;
export type GameCoreCoordinates4 = {
  Position?: GameCoreCoordinates1;
  Rotation?: GameCoreCoordinates5;
} & GameCoreCoordinatesLocalChunkTransform;
export type GameCoreCoordinates5 = {
  Value?: 0 | 1 | 2 | 3;
  MirroredHorizontally?: GameCoreCoordinates5;
  MirroredVertically?: GameCoreCoordinates5;
} & GameCoreCoordinatesGridRotation;
export type GameCoreCoordinatesGridRotation = {
  Value?: 0 | 1 | 2 | 3;
  MirroredHorizontally?: GameCoreCoordinates5;
  MirroredVertically?: GameCoreCoordinates5;
} | null;
export type GameCoreCoordinatesLocalChunkTransform = {
  Position?: GameCoreCoordinates1;
  Rotation?: GameCoreCoordinates5;
} | null;
export type GameCoreCoordinates6 = {
  Position?: GameCoreCoordinates1;
  Direction?: GameCoreCoordinates7;
} & GameCoreCoordinatesLocalChunkPivot;
export type GameCoreCoordinates7 = {
  Value?: 0 | 1 | 2 | 3 | 4 | 5;
  AxisSign?: 0 | 1;
  Axis?: GameCoreCoordinates8;
  Opposite?: GameCoreCoordinates7;
} & GameCoreCoordinatesChunkDirection;
export type GameCoreCoordinates8 = {
  Value?: number;
} & GameCoreCoordinatesChunkAxis;
export type GameCoreCoordinatesChunkAxis = {
  Value?: number;
} | null;
export type GameCoreCoordinatesChunkDirection = {
  Value?: 0 | 1 | 2 | 3 | 4 | 5;
  AxisSign?: 0 | 1;
  Axis?: GameCoreCoordinates8;
  Opposite?: GameCoreCoordinates7;
} | null;
export type GameCoreCoordinatesLocalChunkPivot = {
  Position?: GameCoreCoordinates1;
  Direction?: GameCoreCoordinates7;
} | null;
export type SerializedTransform1 = {
  X?: number;
  Y?: number;
  Z?: number;
  Rotation?: number;
  ToChunkTransform?: GameCoreCoordinates4;
  ToChunkPivot?: GameCoreCoordinates6;
} | null;
export type SerializedConverterModule2 = {
  Transform?: SerializedTransform;
  Name?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedConverterSimpleAnimationModule = SerializedConverterSimpleAnimationModule1[] | null;
export type SerializedConverterSimpleAnimationModule1 = {
  Transform?: SerializedTransform;
  Name?: string | null;
  [k: string]: unknown;
} & SerializedConverterSimpleAnimationModule2;
export type SerializedConverterSimpleAnimationModule2 = {
  Transform?: SerializedTransform;
  Name?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedConverterIOs = {
  Inputs?: SerializedTransform2;
  Outputs?: SerializedTransform2;
  TopUI?: SerializedTransform;
  Rockets?: SerializedConverterModule;
  [k: string]: unknown;
} & SerializedConverterIOs1;
export type SerializedTransform2 = SerializedTransform[] | null;
export type SerializedConverterIOs1 = {
  Inputs?: SerializedTransform2;
  Outputs?: SerializedTransform2;
  TopUI?: SerializedTransform;
  Rockets?: SerializedConverterModule;
  [k: string]: unknown;
} | null;
export type SerializedConverterRecipe = {
  Inputs?: SerializedConverterRecipeInput;
  Outputs?: SerializedConverterRecipeOutput;
  RocketId?: string | null;
  ConversionsPerRocket?: number;
  ConvertersPerFullBelt?: number;
  RequiredUpgradeIds?: System;
  [k: string]: unknown;
} & SerializedConverterRecipe1;
export type SerializedConverterRecipeInput = SerializedConverterRecipeInput1[] | null;
export type SerializedConverterRecipeInput1 = {
  Shape?: string | null;
} & SerializedConverterRecipeInput2;
export type SerializedConverterRecipeInput2 = {
  Shape?: string | null;
} | null;
export type SerializedConverterRecipeOutput = SerializedConverterRecipeOutput1[] | null;
export type SerializedConverterRecipeOutput1 = {
  Shape?: string | null;
} & SerializedConverterRecipeOutput2;
export type SerializedConverterRecipeOutput2 = {
  Shape?: string | null;
} | null;
export type SerializedConverterRecipe1 = {
  Inputs?: SerializedConverterRecipeInput;
  Outputs?: SerializedConverterRecipeOutput;
  RocketId?: string | null;
  ConversionsPerRocket?: number;
  ConvertersPerFullBelt?: number;
  RequiredUpgradeIds?: System;
  [k: string]: unknown;
} | null;
export type SerializedConverterConfig1 = {
  Title?: string | null;
  Description?: string | null;
  Icon?: string | null;
  ChunkCost?: number;
  IsSelectable?: boolean;
  IsBuildable?: boolean;
  IsRemovable?: boolean;
  AccentColorPaletteIndex?: number;
  Modules?: SerializedConverterModule;
  SimpleAnimationModules?: SerializedConverterSimpleAnimationModule;
  IOs?: SerializedConverterIOs;
  Recipe?: SerializedConverterRecipe;
  [k: string]: unknown;
} | null;
export type SerializedConvertersConfig1 = {
  RocketGroups?: SerializedRocketGroup;
  Configs?: {
    [k: string]: SerializedConverterConfig;
  } | null;
  [k: string]: unknown;
} | null;
export type SerializedResearchStationConfig = {
  Recipes?: {
    [k: string]: string | null;
  } | null;
  [k: string]: unknown;
} & SerializedResearchStationConfig1;
export type SerializedResearchStationConfig1 = {
  Recipes?: {
    [k: string]: string | null;
  } | null;
  [k: string]: unknown;
} | null;
export type SerializedRailColorsConfig = {
  RailColors?: SystemCollectionsGenericList1SerializableRailColorSPZGameAssemblyVersion000;
  [k: string]: unknown;
} & SerializedRailColorsConfig1;
export type SystemCollectionsGenericList1SerializableRailColorSPZGameAssemblyVersion000 =
  | SerializableRailColor[]
  | null;
export type SerializableRailColor = {
  Id?: GameCoreRails;
  Tint?: UnityEngine;
  [k: string]: unknown;
} & SerializableRailColor1;
export type GameCoreRails = {
  RailColorId?: string | null;
  [k: string]: unknown;
} & GameCoreRailsSerializableRailColorId;
export type GameCoreRailsSerializableRailColorId = {
  RailColorId?: string | null;
  [k: string]: unknown;
} | null;
export type UnityEngine = {
  r?: number;
  g?: number;
  b?: number;
  a?: number;
  grayscale?: number;
  linear?: UnityEngine;
  gamma?: UnityEngine;
  maxColorComponent?: number;
} & UnityEngineColor;
export type UnityEngineColor = {
  r?: number;
  g?: number;
  b?: number;
  a?: number;
  grayscale?: number;
  linear?: UnityEngine;
  gamma?: UnityEngine;
  maxColorComponent?: number;
} | null;
export type SerializableRailColor1 = {
  Id?: GameCoreRails;
  Tint?: UnityEngine;
  [k: string]: unknown;
} | null;
export type SerializedRailColorsConfig1 = {
  RailColors?: SystemCollectionsGenericList1SerializableRailColorSPZGameAssemblyVersion000;
  [k: string]: unknown;
} | null;
export type LazySerializedToolbarConfig = {
  ToolbarDataJson?: string | null;
  Value?: string | null;
  [k: string]: unknown;
} & LazySerializedToolbarConfig1;
export type LazySerializedToolbarConfig1 = {
  ToolbarDataJson?: string | null;
  Value?: string | null;
  [k: string]: unknown;
} | null;
export type SerializedCinematicIntroConfig = {
  Steps?: SerializedCinematicIntroStep;
  [k: string]: unknown;
} & SerializedCinematicIntroConfig1;
export type SerializedCinematicIntroStep = SerializedCinematicIntroStep1[] | null;
export type SerializedCinematicIntroStep1 = {
  PositionX?: number;
  PositionY?: number;
  Zoom?: number;
  RotationDegrees?: number;
  Angle?: number;
  Text?: string | null;
  TransitionDuration?: number;
  [k: string]: unknown;
} & SerializedCinematicIntroStep2;
export type SerializedCinematicIntroStep2 = {
  PositionX?: number;
  PositionY?: number;
  Zoom?: number;
  RotationDegrees?: number;
  Angle?: number;
  Text?: string | null;
  TransitionDuration?: number;
  [k: string]: unknown;
} | null;
export type SerializedCinematicIntroConfig1 = {
  Steps?: SerializedCinematicIntroStep;
  [k: string]: unknown;
} | null;

export interface SerializedGameScenario {
  FormatVersion: number;
  GameVersion: number;
  UniqueId: string | null;
  IsTutorial: boolean;
  SupportedGameModes: System;
  NextScenarios?: System;
  ExampleShapes?: System;
  Title: string | null;
  Description: string | null;
  PreviewImageId: string | null;
  PlayerBadge: SerializedPlayerBadge;
  ResearchConfig: SerializedResearchConfig;
  Progression: SerializedResearchProgression;
  StartingLocation: SerializedStartingLocationData;
  PlayerLevelConfig: SerializedResearchPlayerLevelConfig;
  Mechanics: SerializedResearchMechanics;
  ConvertersConfig: SerializedConvertersConfig;
  ResearchStationConfig: SerializedResearchStationConfig;
  RailColorsConfig: SerializedRailColorsConfig;
  ToolbarConfig: LazySerializedToolbarConfig;
  CinematicIntroConfig: SerializedCinematicIntroConfig;
  [k: string]: unknown;
}
