include:
  - caddy-volumes.compose.yml
  - pocketbase-volumes.compose.yml

name: shapez-vortex
services:
  proxy:
    extends:
      file: caddy-services.compose.yml
      service: caddy
  db:
    extends:
      file: pocketbase-services.compose.yml
      service: pocketbase
