include:
  - pocketbase-volumes.compose.yml

name: shapez-vortex-development
services:
  db:
    extends:
      file: pocketbase-services.compose.yml
      service: pocketbase
    ports:
      - 8080:8080
    volumes:
      - ./pb_migrations:/pb/pb_migrations
