services:
  pocketbase:
    container_name: shapez-base
    image: ghcr.io/dontmash/shapez-base
    build:
      dockerfile: pocketbase.dockerfile
    restart: unless-stopped
    volumes:
      - db-data:/pb/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
