services:
  nginx:
    container_name: shapez-nginx
    restart: unless-stopped
    image: shapez-nginx
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
