<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/buildings/Lift1UpBackwardInternalVariant_Layer0.glb -s -k -P -t -u -r /models/buildings/
-->

<script
  module
  lang="ts"
>
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      Lift1UpBackwardInternalVariant: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(
      useGltf<GLTFResult>('/models/buildings/Lift1UpBackwardInternalVariant_Layer0.glb')
    )
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group | undefined }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  const gltf = load()
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Lift1UpBackwardInternalVariant"
      castShadow
      receiveShadow
      geometry={gltf.nodes.Lift1UpBackwardInternalVariant.geometry}
      material={gltf.nodes.Lift1UpBackwardInternalVariant.material}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
