/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ScenarioParametersPresetSchemaSchema {
  Version?: number;
  UniqueId?: string | null;
  Title?: string | null;
  Description?: string | null;
  Parameters?: {
    MapGenerationParameters?: {
      FluidsSpawnPrimaryColors?: boolean;
      FluidsSpawnSecondaryColors?: boolean;
      FluidsSpawnTertiaryColors?: boolean;
      FluidPatchLikelinessPercent?: number;
      FluidPatchBaseSize?: number;
      FluidPatchSizeGrowPercentPerChunk?: number;
      FluidPatchMaxSize?: number;
      ShapePatchLikelinessPercent?: number;
      ShapePatchBaseSize?: number;
      ShapePatchSizeGrowPercentPerChunk?: number;
      ShapePatchMaxSize?: number;
      ShapePatchShapeColorfulnessPercent?: number;
      ShapePatchRareShapeLikelinessPercent?: number;
      ShapePatchVeryRareShapeLikelinessPercent?: number;
      ShapePatchGenerationLikeliness?:
        | ({
            GenerationType?:
              | 0
              | 1
              | 2
              | 3
              | 4
              | 5
              | 6
              | 7
              | 8
              | 9
              | 10
              | 11
              | 12
              | 13
              | 14
              | 15;
            MinimumDistanceToOrigin?: number;
            LikelinessPerMille?: number;
            [k: string]: unknown;
          } | null)[]
        | null;
      [k: string]: unknown;
    } | null;
    GameRuleParameters?: {
      RuleIds?: (string | null)[] | null;
      [k: string]: unknown;
    } | null;
    ScenarioId?: string | null;
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}
