/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DifficultyPresetSchemaSchema {
  Version?: number;
  UniqueId?: string | null;
  Title?: string | null;
  Parameters?: {
    ResearchShapeCostMultiplier?: number;
    ChunkLimitMultiplier?: number;
    BlueprintCostMultiplier?: number;
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}
