/* eslint-disable */
/**
 * This file was automatically generated by prepare:schemas.
 * DO NOT MODIFY IT BY HAND.
 */

export type GameCoreMode = {
  ResearchShapeCostMultiplier?: number;
  ChunkLimitMultiplier?: number;
  BlueprintCostMultiplier?: number;
  [k: string]: unknown;
} & GameCoreModeDifficultyGameParametersSerializedData;
export type GameCoreModeDifficultyGameParametersSerializedData = {
  ResearchShapeCostMultiplier?: number;
  ChunkLimitMultiplier?: number;
  BlueprintCostMultiplier?: number;
  [k: string]: unknown;
} | null;

export interface GameCoreGameDataPresetsSerializedGameDifficultyPreset {
  Version: number;
  UniqueId: string | null;
  Title: string | null;
  Parameters: GameCoreMode;
  [k: string]: unknown;
}
