/* eslint-disable */
/**
 * This file was automatically generated by prepare:schemas.
 * DO NOT MODIFY IT BY HAND.
 */

export type GameCoreMode = {
  MapGenerationParameters?: GameCoreMode1;
  GameRuleParameters?: GameCoreMode4;
  ScenarioId?: string | null;
  [k: string]: unknown;
} & GameCoreModeScenarioGameParametersSerializedData;
export type GameCoreMode1 = {
  FluidsSpawnPrimaryColors?: boolean;
  FluidsSpawnSecondaryColors?: boolean;
  FluidsSpawnTertiaryColors?: boolean;
  FluidPatchLikelinessPercent?: number;
  FluidPatchBaseSize?: number;
  FluidPatchSizeGrowPercentPerChunk?: number;
  FluidPatchMaxSize?: number;
  ShapePatchLikelinessPercent?: number;
  ShapePatchBaseSize?: number;
  ShapePatchSizeGrowPercentPerChunk?: number;
  ShapePatchMaxSize?: number;
  ShapePatchShapeColorfulnessPercent?: number;
  ShapePatchRareShapeLikelinessPercent?: number;
  ShapePatchVeryRareShapeLikelinessPercent?: number;
  SpiralGeneration?: boolean;
  SpiralThickness?: number;
  SpiralTwist?: number;
  ShapePatchGenerationLikeliness?: GameCoreMode2;
  [k: string]: unknown;
} & GameCoreModeMapGenerationParametersSerializedData;
export type GameCoreMode2 = GameCoreMode3[] | null;
export type GameCoreMode3 = {
  GenerationType?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  MinimumDistanceToOrigin?: number;
  Weight?: number;
  MaximumDistanceToOrigin?: number;
  [k: string]: unknown;
} & GameCoreModeSerializedMapGenerationShapeLikeliness;
export type GameCoreModeSerializedMapGenerationShapeLikeliness = {
  GenerationType?: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;
  MinimumDistanceToOrigin?: number;
  Weight?: number;
  MaximumDistanceToOrigin?: number;
  [k: string]: unknown;
} | null;
export type GameCoreModeMapGenerationParametersSerializedData = {
  FluidsSpawnPrimaryColors?: boolean;
  FluidsSpawnSecondaryColors?: boolean;
  FluidsSpawnTertiaryColors?: boolean;
  FluidPatchLikelinessPercent?: number;
  FluidPatchBaseSize?: number;
  FluidPatchSizeGrowPercentPerChunk?: number;
  FluidPatchMaxSize?: number;
  ShapePatchLikelinessPercent?: number;
  ShapePatchBaseSize?: number;
  ShapePatchSizeGrowPercentPerChunk?: number;
  ShapePatchMaxSize?: number;
  ShapePatchShapeColorfulnessPercent?: number;
  ShapePatchRareShapeLikelinessPercent?: number;
  ShapePatchVeryRareShapeLikelinessPercent?: number;
  SpiralGeneration?: boolean;
  SpiralThickness?: number;
  SpiralTwist?: number;
  ShapePatchGenerationLikeliness?: GameCoreMode2;
  [k: string]: unknown;
} | null;
export type GameCoreMode4 = {
  RuleIds?: System;
  [k: string]: unknown;
} & GameCoreModeGameRuleParametersSerializedData;
export type System = (string | null)[] | null;
export type GameCoreModeGameRuleParametersSerializedData = {
  RuleIds?: System;
  [k: string]: unknown;
} | null;
export type GameCoreModeScenarioGameParametersSerializedData = {
  MapGenerationParameters?: GameCoreMode1;
  GameRuleParameters?: GameCoreMode4;
  ScenarioId?: string | null;
  [k: string]: unknown;
} | null;

export interface GameCoreGameDataPresetsSerializedGameScenarioParametersPreset {
  Version: number;
  UniqueId: string | null;
  Title: string | null;
  Description: string | null;
  Parameters: GameCoreMode;
  [k: string]: unknown;
}
