/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ScenarioSchemaSchema {
  FormatVersion?: number;
  GameVersion?: number;
  UniqueId?: string | null;
  SupportedGameModes?: (string | null)[] | null;
  ExampleShapes?: (string | null)[] | null;
  BasedOnScenarioId?: string | null;
  FollowupScenarioIds?: (string | null)[] | null;
  RecommendedScenarioIdsToCompleteBefore?: (string | null)[] | null;
  Title?: string | null;
  Description?: string | null;
  PreviewImageId?: string | null;
  Config?: {
    BaseChunkLimitMultiplier?: number;
    BaseBlueprintRewardMultiplier?: number;
    MaxShapeLayers?: number;
    InitialResearchPoints?: number;
    EstimatedUpcomingUpgradesFromFollowup?: number;
    LayerMechanicIds?: (string | null)[] | null;
    BlueprintsMechanicId?: string | null;
    RailsMechanicId?: string | null;
    IslandManagementMechanicId?: string | null;
    PlayerLevelMechanicId?: string | null;
    TrainHubDeliveryMechanicId?: string | null;
    ShapesConfigurationId?: string | null;
    ColorSchemeConfigurationId?: string | null;
    BlueprintCurrencyShapes?:
      | ({
          Shape?: string | null;
          RequiredUpgradeId?: string | null;
          Amount?: number;
          [k: string]: unknown;
        } | null)[]
      | null;
    HubInputSizeUpgradeId?: string | null;
    ShapeQuantityUpgradeId?: string | null;
    SpeedsToLinearUpgradeMappings?: {
      [k: string]: string | null;
    } | null;
    IntroductionWikiEntryId?: string | null;
    InitiallyUnlockedUpgrades?: (string | null)[] | null;
    TutorialConfig?: string | null;
    PlayerLevelConfig?: {
      IconicLevelShapes?: (string | null)[] | null;
      IconicLevelShapeInterval?: number;
      GoalLines?:
        | ({
            Id?: string | null;
            Randomized?: boolean;
            RandomizedUseCrystals?: boolean;
            Shape?: string | null;
            StartingAmount?: number;
            ExponentialGrowthPercentPerLevel?: number;
            RequiredUpgrade?: string | null;
          } | null)[]
        | null;
      Rewards?:
        | ({
            MinimumLevel?: number;
            Rewards?:
              | ({
                  [k: string]: unknown;
                } | null)[]
              | null;
          } | null)[]
        | null;
      [k: string]: unknown;
    } | null;
    [k: string]: unknown;
  } | null;
  Progression?: {
    Levels?:
      | ({
          Id?: string | null;
          Rewards?:
            | ({
                [k: string]: unknown;
              } | null)[]
            | null;
          VideoId?: string | null;
          PreviewImageId?: string | null;
          Title?: string | null;
          Description?: string | null;
          WikiEntryId?: string | null;
          Lines?:
            | ({
                ReusedAtNextMilestone?: boolean;
                ReusedAtNextMilestoneOffset?: number;
                ReusedAtSameMilestone?: boolean;
                ReusedAtSameMilestoneOffset?: number;
                ReusedForPlayerLevel?: boolean;
                StartingOffset?: number;
                Shapes?:
                  | ({
                      Shape?: string | null;
                      Amount?: number;
                      [k: string]: unknown;
                    } | null)[]
                  | null;
                [k: string]: unknown;
              } | null)[]
            | null;
          [k: string]: unknown;
        } | null)[]
      | null;
    SideQuestGroups?:
      | ({
          Title?: string | null;
          RequiredUpgradeIds?: (string | null)[] | null;
          SideQuests?:
            | ({
                Id?: string | null;
                IsFollowupForLevel?: boolean;
                Rewards?:
                  | ({
                      [k: string]: unknown;
                    } | null)[]
                  | null;
                Costs?:
                  | ({
                      Shape?: string | null;
                      Amount?: number;
                      [k: string]: unknown;
                    } | null)[]
                  | null;
                [k: string]: unknown;
              } | null)[]
            | null;
          [k: string]: unknown;
        } | null)[]
      | null;
    SideUpgrades?:
      | ({
          Id?: string | null;
          PreviewImageId?: string | null;
          VideoId?: string | null;
          Title?: string | null;
          Description?: string | null;
          Hidden?: boolean;
          RequiredUpgradeIds?: (string | null)[] | null;
          Rewards?:
            | ({
                [k: string]: unknown;
              } | null)[]
            | null;
          Costs?:
            | ({
                [k: string]: unknown;
              } | null)[]
            | null;
          [k: string]: unknown;
        } | null)[]
      | null;
    LinearUpgrades?:
      | ({
          Id?: string | null;
          Title?: string | null;
          Levels?:
            | ({
                Value?: number;
                Cost?: {
                  [k: string]: unknown;
                } | null;
              } | null)[]
            | null;
          RequiredUpgradeId?: string | null;
          [k: string]: unknown;
        } | null)[]
      | null;
    Mechanics?:
      | ({
          Id?: string | null;
          Title?: string | null;
          Description?: string | null;
          IconId?: string | null;
          [k: string]: unknown;
        } | null)[]
      | null;
    [k: string]: unknown;
  } | null;
  StartingLocation?: {
    Hub?: {
      Position_GC?: {
        x?: number;
        y?: number;
      } | null;
      Rotation?: number;
      LayoutId?: string | null;
    } | null;
    InitialViewport?: {
      PositionX?: number;
      PositionY?: number;
      Zoom?: number;
      RotationDegrees?: number;
      Angle?: number;
      Layer?: number;
      ShowAllLayers?: boolean;
      [k: string]: unknown;
    } | null;
    InitialIslands?:
      | ({
          Position_GC?: {
            x?: number;
            y?: number;
          } | null;
          Rotation?: number;
          LayoutId?: string | null;
        } | null)[]
      | null;
    FixedPatches?:
      | ({
          Shape?: string | null;
          Position_LC?: {
            x?: number;
            y?: number;
          } | null;
          LocalTiles?:
            | ({
                x?: number;
                y?: number;
              } | null)[]
            | null;
          [k: string]: unknown;
        } | null)[]
      | null;
    StartingChunks?:
      | ({
          SuperChunk?: {
            x?: number;
            y?: number;
          } | null;
          GuaranteedShapePatches?: (string | null)[] | null;
          GuaranteedColorPatches?: string[] | null;
          DoNotGenerateOtherResources?: boolean;
          [k: string]: unknown;
        } | null)[]
      | null;
    [k: string]: unknown;
  } | null;
  [k: string]: unknown;
}
