import type { ShapeIdentifier } from '@shapez-vortex/shape';

export {
  SHAPE_DEFAULT_TYPES,
  SHAPE_DEFAULT_TYPE_IDENTIFIERS,
  SHAPE_HEX_TYPES,
  SHAPE_HEX_TYPE_IDENTIFIER,
  SHAPE_TYPE_IDENTIFIER,
  SHAPE_COLORS,
  SHAPE_COLOR_IDENTIFIERS,
  SHAPE_LAYER_IDENTIFIER_SEPERATOR,
  SHAPE_PART_REGEX,
  SHAPE_PART_PARAMETERS_REGEX,
  SHAPE_MAX_LAYERS,
  SHAPE_MAX_DEFAULT_PARTS,
  SHAPE_MAX_HEX_PARTS,
  isDefaultShapeIdentifier,
  isHexShapeIdentifier,
  isShapeIdentifier,
  parse,
  stringify,
  random,
  getTypes,
  getColors,
  getLayerCount,
  getPartCount,
  type ShapeData,
  type ShapeIdentifier,
  type ShapeDefaultType,
  type ShapeDefaultTypeIdentifier,
  type ShapeHexTypes,
  type ShapeHexTypeIdentifier,
  type ShapeType,
  type ShapeTypeIdentifier,
  type ShapeColor,
  type ShapeColorIdentifier,
  type Shape,
  type ShapeLayerData,
  type ShapePartData,
} from '@shapez-vortex/shape';

export const DEFAULT_SHAPE: ShapeIdentifier =
  'CwRwCwCw:P-P-P-P-:P-P-P-P-:CcCcCcCc';
