<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/buildings/CutterHalfInternalVariant.gltf -s -k -P -t -u -r /models/buildings/
-->

<script context="module" lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      HalfCutter_Robot_Joint1_LOD0: THREE.Mesh
      HalfCutter_Robot_Joint2_LOD0: THREE.Mesh
      HalfCutter_Robot_Joint3_LOD0: THREE.Mesh
      HalfCutter_Default_Laser_LOD0: THREE.Mesh
      HalfCutter_Default_Plattform_LOD0: THREE.Mesh
      HalfCutter_Default_PlattformMain_LOD0: THREE.Mesh
      HalfCutter_Default_Main_LOD0: THREE.Mesh
      HalfCutter_Default_Shield_LOD0: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf<GLTFResult>('/models/buildings/CutterHalfInternalVariant.gltf'))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  const gltf = load()

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      name="HalfCutter_Robot_Joint1_LOD0"
      castShadow
      receiveShadow
      geometry={gltf.nodes.HalfCutter_Robot_Joint1_LOD0.geometry}
      material={gltf.nodes.HalfCutter_Robot_Joint1_LOD0.material}
      position={[-0.05, 0.34, -0.33]}
    >
      <T.Mesh
        name="HalfCutter_Robot_Joint2_LOD0"
        castShadow
        receiveShadow
        geometry={gltf.nodes.HalfCutter_Robot_Joint2_LOD0.geometry}
        material={gltf.nodes.HalfCutter_Robot_Joint2_LOD0.material}
        position={[0.04, 0.2, -0.04]}
      >
        <T.Mesh
          name="HalfCutter_Robot_Joint3_LOD0"
          castShadow
          receiveShadow
          geometry={gltf.nodes.HalfCutter_Robot_Joint3_LOD0.geometry}
          material={gltf.nodes.HalfCutter_Robot_Joint3_LOD0.material}
          position={[-0.02, 0.13, 0.13]}
        />
      </T.Mesh>
    </T.Mesh>
    <T.Mesh
      name="HalfCutter_Default_Laser_LOD0"
      castShadow
      receiveShadow
      geometry={gltf.nodes.HalfCutter_Default_Laser_LOD0.geometry}
      material={gltf.nodes.HalfCutter_Default_Laser_LOD0.material}
    />
    <T.Mesh
      name="HalfCutter_Default_Plattform_LOD0"
      castShadow
      receiveShadow
      geometry={gltf.nodes.HalfCutter_Default_Plattform_LOD0.geometry}
      material={gltf.nodes.HalfCutter_Default_Plattform_LOD0.material}
    />
    <T.Mesh
      name="HalfCutter_Default_PlattformMain_LOD0"
      castShadow
      receiveShadow
      geometry={gltf.nodes.HalfCutter_Default_PlattformMain_LOD0.geometry}
      material={gltf.nodes.HalfCutter_Default_PlattformMain_LOD0.material}
    />
    <T.Mesh
      name="HalfCutter_Default_Main_LOD0"
      castShadow
      receiveShadow
      geometry={gltf.nodes.HalfCutter_Default_Main_LOD0.geometry}
      material={gltf.nodes.HalfCutter_Default_Main_LOD0.material}
    />
    <T.Mesh
      name="HalfCutter_Default_Shield_LOD0"
      castShadow
      receiveShadow
      geometry={gltf.nodes.HalfCutter_Default_Shield_LOD0.geometry}
      material={gltf.nodes.HalfCutter_Default_Shield_LOD0.material}
      rotation={[Math.PI / 2, 0, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
