<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/buildings/FluidPortSenderInternalVariant.gltf -s -k -P -t -u -r /models/buildings/
-->

<script context="module" lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      BeltPort_Sender_Main_LOD0002: THREE.Mesh
      FluidBridgeSender_Container_Glass001: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf<GLTFResult>('/models/buildings/FluidPortSenderInternalVariant.gltf'))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  const gltf = load()

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      name="BeltPort_Sender_Main_LOD0002"
      castShadow
      receiveShadow
      geometry={gltf.nodes.BeltPort_Sender_Main_LOD0002.geometry}
      material={gltf.nodes.BeltPort_Sender_Main_LOD0002.material}
    />
    <T.Mesh
      name="FluidBridgeSender_Container_Glass001"
      castShadow
      receiveShadow
      geometry={gltf.nodes.FluidBridgeSender_Container_Glass001.geometry}
      material={gltf.nodes.FluidBridgeSender_Container_Glass001.material}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
