<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/buildings/LabelDefaultInternalVariant.gltf -s -k -P -t -u -r /models/buildings/
-->

<script
  module
  lang="ts"
>
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      LabelSupport: THREE.Mesh
      LabelSupport_A: THREE.Mesh
      LabelSupport_B: THREE.Mesh
      LabelSupport_C: THREE.Mesh
      LabelSupport_D: THREE.Mesh
      LabelSupport_E: THREE.Mesh
      LabelSupport_F: THREE.Mesh
      LabelSupport_G: THREE.Mesh
      LabelSupport_H: THREE.Mesh
      LabelSupport_I: THREE.Mesh
      LabelSupport_J: THREE.Mesh
      LabelSupport_K: THREE.Mesh
      LabelSupport_L: THREE.Mesh
      LabelSupport_M: THREE.Mesh
      LabelSupport_N: THREE.Mesh
      LabelSupport_O: THREE.Mesh
      LabelSupport_P: THREE.Mesh
      LabelSupport_Q: THREE.Mesh
      LabelSupport_R: THREE.Mesh
      LabelSupport_S: THREE.Mesh
      LabelSupport_T: THREE.Mesh
      LabelSupport_U: THREE.Mesh
      LabelSupport_V: THREE.Mesh
      LabelSupport_W: THREE.Mesh
      LabelSupport_X: THREE.Mesh
      LabelSupport_Y: THREE.Mesh
      LabelSupport_Z: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf<GLTFResult>('/models/buildings/LabelDefaultInternalVariant.gltf'))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  const gltf = load()
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="LabelSupport"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport.geometry}
      material={gltf.nodes.LabelSupport.material}
    />
    <T.Mesh
      name="LabelSupport_A"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_A.geometry}
      material={gltf.nodes.LabelSupport_A.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_B"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_B.geometry}
      material={gltf.nodes.LabelSupport_B.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_C"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_C.geometry}
      material={gltf.nodes.LabelSupport_C.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_D"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_D.geometry}
      material={gltf.nodes.LabelSupport_D.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_E"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_E.geometry}
      material={gltf.nodes.LabelSupport_E.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_F"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_F.geometry}
      material={gltf.nodes.LabelSupport_F.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_G"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_G.geometry}
      material={gltf.nodes.LabelSupport_G.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_H"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_H.geometry}
      material={gltf.nodes.LabelSupport_H.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_I"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_I.geometry}
      material={gltf.nodes.LabelSupport_I.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_J"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_J.geometry}
      material={gltf.nodes.LabelSupport_J.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_K"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_K.geometry}
      material={gltf.nodes.LabelSupport_K.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_L"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_L.geometry}
      material={gltf.nodes.LabelSupport_L.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_M"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_M.geometry}
      material={gltf.nodes.LabelSupport_M.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_N"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_N.geometry}
      material={gltf.nodes.LabelSupport_N.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_O"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_O.geometry}
      material={gltf.nodes.LabelSupport_O.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_P"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_P.geometry}
      material={gltf.nodes.LabelSupport_P.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_Q"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_Q.geometry}
      material={gltf.nodes.LabelSupport_Q.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_R"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_R.geometry}
      material={gltf.nodes.LabelSupport_R.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_S"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_S.geometry}
      material={gltf.nodes.LabelSupport_S.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_T"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_T.geometry}
      material={gltf.nodes.LabelSupport_T.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_U"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_U.geometry}
      material={gltf.nodes.LabelSupport_U.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_V"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_V.geometry}
      material={gltf.nodes.LabelSupport_V.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_W"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_W.geometry}
      material={gltf.nodes.LabelSupport_W.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_X"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_X.geometry}
      material={gltf.nodes.LabelSupport_X.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_Y"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_Y.geometry}
      material={gltf.nodes.LabelSupport_Y.material}
      position={[1.9, 0.26, 0]}
    />
    <T.Mesh
      name="LabelSupport_Z"
      castShadow
      receiveShadow
      geometry={gltf.nodes.LabelSupport_Z.geometry}
      material={gltf.nodes.LabelSupport_Z.material}
      position={[1.9, 0.26, 0]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
