<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/buildings/Pipe2UpForwardInternalVariant.gltf -s -k -P -t -u -r /models/buildings/
-->

<script
  module
  lang="ts"
>
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      PipeBake_SolidIn_Layer0_LOD0004: THREE.Mesh
      PipeBake_Rotator_LOD0007: THREE.Mesh
      PipeBake_Pump_LOD0007: THREE.Mesh
      PipeBake_Upward_Solid1_LOD0001: THREE.Mesh
      PipeBake_2Up_Glas_LOD0001: THREE.Mesh
      PipeBake_UpFoward_Glas_LOD0007: THREE.Mesh
      PipeBake_ForwardUp_Glas_LOD0007: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf<GLTFResult>('/models/buildings/Pipe2UpForwardInternalVariant.gltf'))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  const gltf = load()
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="PipeBake_SolidIn_Layer0_LOD0004"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_SolidIn_Layer0_LOD0004.geometry}
      material={gltf.nodes.PipeBake_SolidIn_Layer0_LOD0004.material}
    />
    <T.Mesh
      name="PipeBake_Rotator_LOD0007"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_Rotator_LOD0007.geometry}
      material={gltf.nodes.PipeBake_Rotator_LOD0007.material}
    />
    <T.Mesh
      name="PipeBake_Pump_LOD0007"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_Pump_LOD0007.geometry}
      material={gltf.nodes.PipeBake_Pump_LOD0007.material}
    />
    <T.Mesh
      name="PipeBake_Upward_Solid1_LOD0001"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_Upward_Solid1_LOD0001.geometry}
      material={gltf.nodes.PipeBake_Upward_Solid1_LOD0001.material}
      position={[0, 2, 0]}
    />
    <T.Mesh
      name="PipeBake_2Up_Glas_LOD0001"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_2Up_Glas_LOD0001.geometry}
      material={gltf.nodes.PipeBake_2Up_Glas_LOD0001.material}
    />
    <T.Mesh
      name="PipeBake_UpFoward_Glas_LOD0007"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_UpFoward_Glas_LOD0007.geometry}
      material={gltf.nodes.PipeBake_UpFoward_Glas_LOD0007.material}
    />
    <T.Mesh
      name="PipeBake_ForwardUp_Glas_LOD0007"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_ForwardUp_Glas_LOD0007.geometry}
      material={gltf.nodes.PipeBake_ForwardUp_Glas_LOD0007.material}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
