<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/buildings/PipeUpBackwardInternalVariant_Layer0.gltf -s -k -P -t -u -r /models/buildings/
-->

<script context="module" lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      PipeBake_SolidIn_Layer0_LOD0003: THREE.Mesh
      PipeBake_ForwardUp_Glas_LOD0005: THREE.Mesh
      PipeBake_Rotator_LOD0005: THREE.Mesh
      PipeBake_Pump_LOD0005: THREE.Mesh
      PipeBake_UpFoward_Glas_LOD0005: THREE.Mesh
      PipeBake_SolidOut_Layer1_LOD0003: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf<GLTFResult>('/models/buildings/PipeUpBackwardInternalVariant_Layer0.gltf'))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  const gltf = load()

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      name="PipeBake_SolidIn_Layer0_LOD0003"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_SolidIn_Layer0_LOD0003.geometry}
      material={gltf.nodes.PipeBake_SolidIn_Layer0_LOD0003.material}
    />
    <T.Mesh
      name="PipeBake_ForwardUp_Glas_LOD0005"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_ForwardUp_Glas_LOD0005.geometry}
      material={gltf.nodes.PipeBake_ForwardUp_Glas_LOD0005.material}
    />
    <T.Mesh
      name="PipeBake_Rotator_LOD0005"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_Rotator_LOD0005.geometry}
      material={gltf.nodes.PipeBake_Rotator_LOD0005.material}
    />
    <T.Mesh
      name="PipeBake_Pump_LOD0005"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_Pump_LOD0005.geometry}
      material={gltf.nodes.PipeBake_Pump_LOD0005.material}
    />
    <T.Mesh
      name="PipeBake_UpFoward_Glas_LOD0005"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_UpFoward_Glas_LOD0005.geometry}
      material={gltf.nodes.PipeBake_UpFoward_Glas_LOD0005.material}
      position={[0, -1, 0]}
      rotation={[Math.PI, 0, Math.PI]}
    />
    <T.Mesh
      name="PipeBake_SolidOut_Layer1_LOD0003"
      castShadow
      receiveShadow
      geometry={gltf.nodes.PipeBake_SolidOut_Layer1_LOD0003.geometry}
      material={gltf.nodes.PipeBake_SolidOut_Layer1_LOD0003.material}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
