import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile } from 'json-schema-to-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../');

async function processSchema(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  let schema;
  try {
    schema = JSON.parse(content);
  } catch (e) {
    console.error(`Invalid JSON in ${filePath}`);
    throw e;
  }

  const definitions = {};

  // Recursively walk the schema to extract inline definitions
  function extractDefinitions(obj, parent = null, keyInParent = null) {
    if (!obj || typeof obj !== 'object') return;

    // Extract inline IDs
    if (obj.id && obj !== schema) {
      const id = obj.id;

      // If we haven't defined this ID yet, copy its contents
      if (!definitions[id]) {
        const def = { ...obj };
        delete def.id;
        definitions[id] = def;
        // Process children of the definition
        extractDefinitions(definitions[id]);
      }

      // Now replace the original inline object with a $ref
      if (parent && keyInParent !== null) {
        parent[keyInParent] = { $ref: `#/definitions/${id}` };
      }
      return; // Stop processing this object since it was replaced
    }

    // Fix non-standard $refs
    if (obj.$ref && typeof obj.$ref === 'string' && !obj.$ref.startsWith('#')) {
      obj.$ref = `#/definitions/${obj.$ref}`;
    }

    // Fix inline "required" boolean flags
    if (obj.type === 'object' && obj.properties) {
      const requiredArray = obj.required || [];
      const actualRequiredArray = Array.isArray(requiredArray)
        ? requiredArray
        : [];
      let isModified = false;

      for (const [propName, propDef] of Object.entries(obj.properties)) {
        if (
          propDef &&
          typeof propDef === 'object' &&
          propDef.required === true
        ) {
          if (!actualRequiredArray.includes(propName)) {
            actualRequiredArray.push(propName);
            isModified = true;
          }
          delete propDef.required;
        }
      }

      if (actualRequiredArray.length > 0) {
        obj.required = actualRequiredArray;
      } else if (isModified && actualRequiredArray.length === 0) {
        delete obj.required; // remove empty array if we created it
      }
    }

    for (const key of Object.keys(obj)) {
      if (key !== 'required' || typeof obj[key] !== 'boolean') {
        extractDefinitions(obj[key], obj, key);
      }
    }
  }

  extractDefinitions(schema);

  if (Object.keys(definitions).length > 0) {
    schema.definitions = schema.definitions || {};
    Object.assign(schema.definitions, definitions);
  }

  return schema;
}

async function prepareDataFiles() {
  const dataDir = path.resolve(rootDir, 'src/game-data');
  const schemasDir = path.resolve(rootDir, 'src/schemas');

  if (!fs.existsSync(schemasDir)) {
    fs.mkdirSync(schemasDir, { recursive: true });
  }

  // Generate version.ts
  const versionPath = path.resolve(dataDir, 'version.json');
  if (fs.existsSync(versionPath)) {
    const versionStr = fs.readFileSync(versionPath, 'utf-8').trim();
    const versionTs = `/**\n* This file was automatically generated by prepare:schemas.\n* DO NOT MODIFY IT BY HAND.\n*/\nexport const GAME_VERSION = ${versionStr};\n`;
    fs.writeFileSync(path.resolve(schemasDir, 'version.ts'), versionTs);
    console.log(`Generated src/schemas/version.ts`);
  }

  // Generate identifiers.ts
  const identifiersPath = path.resolve(dataDir, 'identifiers.json');
  if (fs.existsSync(identifiersPath)) {
    const identifiersJson = fs.readFileSync(identifiersPath, 'utf-8');
    const identifiersTs = `/**\n* This file was automatically generated by prepare:schemas.\n* DO NOT MODIFY IT BY HAND.\n*/\nexport const identifiers = ${identifiersJson} as const;\n`;
    fs.writeFileSync(path.resolve(schemasDir, 'identifiers.ts'), identifiersTs);
    console.log(`Generated src/schemas/identifiers.ts`);
  }
}

async function main() {
  const inputPattern = 'src/game-data/json-schemas/**/*.json';
  const outDir = path.resolve(rootDir, 'src/schemas');

  console.log(`Finding schemas matching ${inputPattern} in ${rootDir}`);

  await prepareDataFiles();

  // globSync was added in Node 20 or we can use another module, let's use a simple recursive read
  const globPattern = path.resolve(
    rootDir,
    'src/game-data/json-schemas',
  );

  function getFiles(dir, files = []) {
    const list = fs.readdirSync(dir);
    for (const item of list) {
      const fullPath = path.join(dir, item);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        getFiles(fullPath, files);
      } else if (fullPath.endsWith('.json')) {
        files.push(fullPath);
      }
    }
    return files;
  }

  const files = getFiles(globPattern);

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  for (const file of files) {
    const fullPath = path.resolve(rootDir, file);
    console.log(`Processing ${file}`);

    try {
      const sanitizedSchema = await processSchema(fullPath);
      const fileName =
        path.basename(file, '.json').replace('.schema', '') + '.d.ts';
      const outPath = path.resolve(outDir, fileName);

      const tsCode = await compile(
        sanitizedSchema,
        sanitizedSchema.id || path.basename(file, '.json'),
        {
          cwd: rootDir,
          bannerComment: `/* eslint-disable */\n/**\n* This file was automatically generated by prepare:schemas.\n* DO NOT MODIFY IT BY HAND.\n*/`,
          style: {
            singleQuote: true,
          },
        },
      );

      fs.writeFileSync(outPath, tsCode);
      console.log(`Generated ${outPath}`);
    } catch (err) {
      console.error(`Error processing ${file}:`, err);
    }
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
