<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 static/models/shapes/ShapeDefaultC.gltf -k -P -t -u -r /models/shapes/
-->

<script context="module" lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useSuspense } from '@threlte/extras'

  type GLTFResult = {
    nodes: {
      CircleQuad_Viewer: THREE.Mesh
    }
    materials: {}
  }

  const load = () => {
    const suspend = useSuspense()
    return suspend(useGltf<GLTFResult>('/models/shapes/ShapeDefaultC.gltf'))
  }

  export const preload = async () => {
    await load()
  }
</script>

<script lang="ts">
  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  const gltf = load()

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      name="CircleQuad_Viewer"
      geometry={gltf.nodes.CircleQuad_Viewer.geometry}
      material={gltf.nodes.CircleQuad_Viewer.material}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
