name: CD

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        working-directory: ./resources/deployment
        run: |
          docker compose -f compose.production.yml build
          docker tag shapez-base ${{ github.repository_owner }}/shapez-base:latest
          docker tag shapez-base ${{ github.repository_owner }}/shapez-base:${{ github.ref_name }}
          docker tag shapez-proxy ${{ github.repository_owner }}/shapez-proxy:latest
          docker tag shapez-proxy ${{ github.repository_owner }}/shapez-proxy:${{ github.ref_name }}
      - name: Update env
        run: |
          echo "REGISTRY_DIR=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"
      - name: Push
        run: |
          docker image ls
          docker push -a ghcr.io/${{ env.REGISTRY_DIR }}/shapez-base
          docker push -a ghcr.io/${{ env.REGISTRY_DIR }}/shapez-proxy
